{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imove-consumer
  {{- with .Values.consumer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "baseLabels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: "{{ .Values.env }}"
        tags.datadoghq.com/service: "imove-consumer"
        tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
        {{- include "consumer.selectorLabels" . | nindent 8 }}
        {{- with .Values.consumer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: imove-consumer
          image: "{{ .Values.consumer.image.repository }}:consumer-{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.consumer.externalSecretRef.name }}
          resources:
            {{- toYaml .Values.consumer.resources | nindent 12 }}
{{- end }}
