apiVersion: v1
kind: Service
metadata:
  name: imove-api-service
  labels:
    {{- include "baseLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  loadBalancerIP: {{ .Values.api.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
